### ISSUE TITLE
Have derive(Debug) generate similar output as plain enums

### ISSUE THREAD

**Issue by kupiakos** [kupiakos/open-enum#9]
We can intercept a listed `derive(Debug)` to generate output similar to a plain enum, rather than as a newtype without any familiar names.

**Comment by chris-oo** [comment]
Hi! I have a change that I think will address this at my branch here: https://github.com/kupiakos/open-enum/compare/main...chris-oo:open-enum:custom-debug, but I need to figure out how the CLA works since I'm currently at Microsoft.

In the meantime, are there any tests that you'd like me to add? I wasn't too sure from looking at the repo, but happy to do whatever you think is necessary.

**Comment by chris-oo** [comment]
I've gone ahead and added a test and opened the PR.

**Comment by chris-oo** [comment]
Is it possible for you to spin a new crates.io release for this as well? Much appreciated!

**Comment by kupiakos** [comment]
@chris-oo [Done](https://github.com/kupiakos/open-enum/commit/9c1f1b32de5d6294f94a1f71cf69b53df9f9168e), version [0.4.0](https://crates.io/crates/open_enum/0.4.0). It needed some adjustment for doc tests.

**Comment by chris-oo** [comment]
Thanks so much!
